# Generated by Django 3.0.4 on 2020-03-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='leader',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
