# Generated by Django 3.0.4 on 2020-03-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_workarrangment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workarrangment',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee_model',
            name='work',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='assign.Workarrangment'),
            preserve_default=False,
        ),
    ]
