# Generated by Django 3.0.4 on 2020-03-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0004_auto_20200320_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workarrangment',
            name='part_time',
        ),
        migrations.AddField(
            model_name='workarrangment',
            name='work',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
