# Generated by Django 3.0.4 on 2020-03-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0005_auto_20200320_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='work',
        ),
        migrations.DeleteModel(
            name='Workarrangment',
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.Team_model'),
        ),
    ]
