# Generated by Django 3.0.4 on 2020-03-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0006_auto_20200320_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='pay',
        ),
        migrations.AddField(
            model_name='employee_model',
            name='arrangment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='assign.work_model'),
            preserve_default=False,
        ),
    ]
