# Generated by Django 3.0.4 on 2020-03-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0009_auto_20200322_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_model',
            name='arrangment',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='leader',
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.team_model'),
        ),
        migrations.AlterField(
            model_name='leaders_model',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.employee_model', to_field='name'),
        ),
    ]
