# Generated by Django 3.0.4 on 2020-03-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0020_auto_20200325_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='work_time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='pay',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.team_model', to_field='name'),
        ),
        migrations.AlterField(
            model_name='leaders_model',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.employee_model', to_field='name'),
        ),
    ]
